name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip3 install --user --upgrade buildozer Cython==0.29.33 virtualenv

      - name: Build APK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # 'yes |' safety ke liye rakha hai
          yes | ~/.local/bin/buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        # Ye step build hone ke baad APK ko download ke liye ready rakhega
        uses: actions/upload-artifact@v4
        with:
          name: my-flask-app-apk
          path: bin/*.apk
